name: Issue/Feature Request
description: Report an issue or suggest a feature for Bila 
title: "[Feature/Issue]: "
labels: ["needs-triage"]
body:
  - type: dropdown
    id: request-type
    attributes:
      label: Request Type
      description: Is this an issue report or feature request?
      options:
        - Bug/Issue Report
        - Feature Request
        - Enhancement
        - Security Concern
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What area does this relate to?
      options:
        - Payments
        - User Authentication
        - API Integration
        - Mobile App
        - Web Platform
        - Security
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the issue or feature you'd like to see
      placeholder: Provide a clear and detailed explanation...
    validations:
      required: true

  - type: textarea
    id: expected-impact
    attributes:
      label: Expected Impact
      description: How will this improve Bila's services?
      placeholder: This will help by...
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information that might be relevant
      placeholder: Add any other context or screenshots here

  - type: checkboxes
    id: terms
    attributes:
      label: Confirmation
      options:
        - label: I understand this information will be publicly visible
          required: true
